services:
  - type: web
    name: genz2
    runtime: docker
    buildCommand: docker build -t genz2 .
    startCommand: docker run -p $PORT:3000 genz2
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
        sync: false
